services:
  backend:
    build:
      context: ./apps/backend
    ports:
      - "8080:8080"

  public-frontend:
    build:
      context: ./apps/public-frontend
    ports:
      - "3000:3000"

  admin-frontend:
    build:
      context: ./apps/admin-frontend
    ports:
      - "3001:3001"
