services:
  backend:
    build:
      context: ./apps/backend
    ports:
      - '8081:8081'

  public-frontend:
    build:
      context: ./apps/public-frontend
    ports:
      - '3000:3000'

  admin-frontend:
    build:
      context: ./apps/admin-frontend
    ports:
      - '3001:3001'
