create table audit_logs (
    id bigint generated by default as identity primary key,
    action varchar(255) not null,
    actor varchar(255) not null,
    target_email varchar(255),
    details varchar(2000),
    created_at timestamp with time zone not null
);

create table roles (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    description varchar(255) not null
);

create table employee_directory_snapshot (
    employee_id varchar(255) primary key,
    full_name varchar(255) not null,
    email varchar(255) not null unique,
    active boolean not null
);

create table users (
    id bigint generated by default as identity primary key,
    employee_id varchar(255) not null unique,
    full_name varchar(255) not null,
    email varchar(255) not null unique,
    password_hash varchar(255),
    preferred_locale varchar(20) not null,
    source varchar(50) not null,
    status varchar(255) not null,
    invite_token varchar(255) unique,
    invite_expires_at timestamp with time zone,
    password_reset_token varchar(255) unique,
    password_reset_expires_at timestamp with time zone,
    created_at timestamp with time zone not null,
    role_id bigint not null,
    constraint fk_users_role foreign key (role_id) references roles (id)
);

create table content_sections (
    id bigint generated by default as identity primary key,
    parent_id bigint,
    type varchar(50) not null,
    sort_order integer not null,
    status varchar(50) not null,
    icon_key varchar(255),
    is_featured boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_content_sections_parent foreign key (parent_id) references content_sections (id)
);

create table content_section_translations (
    id bigint generated by default as identity primary key,
    section_id bigint not null,
    locale varchar(20) not null,
    name varchar(255) not null,
    slug varchar(255) not null,
    summary varchar(2000),
    constraint fk_section_translations_section foreign key (section_id) references content_sections (id),
    constraint uq_section_translation_section_locale unique (section_id, locale),
    constraint uq_section_translation_slug_locale unique (slug, locale)
);

create table content_topics (
    id bigint generated by default as identity primary key,
    section_id bigint not null,
    topic_type varchar(50) not null,
    status varchar(50) not null,
    sort_order integer not null,
    is_featured boolean not null,
    show_in_navigation boolean not null,
    published_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_content_topics_section foreign key (section_id) references content_sections (id)
);

create table content_topic_translations (
    id bigint generated by default as identity primary key,
    topic_id bigint not null,
    locale varchar(20) not null,
    title varchar(255) not null,
    slug varchar(255) not null,
    summary varchar(2000),
    intro_text varchar(8000),
    constraint fk_topic_translations_topic foreign key (topic_id) references content_topics (id),
    constraint uq_topic_translation_topic_locale unique (topic_id, locale),
    constraint uq_topic_translation_slug_locale unique (slug, locale)
);

create table content_topic_blocks (
    id bigint generated by default as identity primary key,
    topic_id bigint not null,
    block_type varchar(50) not null,
    sort_order integer not null,
    status varchar(50) not null,
    anchor_key varchar(255) not null,
    is_highlighted boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_topic_blocks_topic foreign key (topic_id) references content_topics (id)
);

create table content_topic_block_translations (
    id bigint generated by default as identity primary key,
    topic_block_id bigint not null,
    locale varchar(20) not null,
    title varchar(255) not null,
    body varchar(12000),
    constraint fk_topic_block_translations_block foreign key (topic_block_id) references content_topic_blocks (id),
    constraint uq_topic_block_translation_block_locale unique (topic_block_id, locale)
);
