create table email_notifications (
    id bigint generated by default as identity primary key,
    type varchar(50) not null,
    recipient_email varchar(255) not null,
    recipient_name varchar(255) not null,
    token varchar(512) not null,
    token_expires_at timestamp with time zone not null,
    status varchar(50) not null,
    attempts integer not null default 0,
    max_attempts integer not null,
    next_attempt_at timestamp with time zone not null,
    last_attempt_at timestamp with time zone,
    sent_at timestamp with time zone,
    last_error varchar(2000),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_email_notifications_status_next_attempt
    on email_notifications (status, next_attempt_at);
