create table content_topic_workflow_history (
    id bigint generated by default as identity primary key,
    topic_id bigint not null,
    action varchar(50) not null,
    from_status varchar(50) not null,
    to_status varchar(50) not null,
    comment varchar(4000),
    performed_by varchar(255) not null,
    created_at timestamp with time zone not null,
    constraint fk_topic_workflow_history_topic foreign key (topic_id) references content_topics (id) on delete cascade
);

create index idx_topic_workflow_history_topic_created_at
    on content_topic_workflow_history (topic_id, created_at desc);
